POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Thuy",
    "password": "19052007"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "Thuy",
    "password": "19052007"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json

{   
    "description": "abc",
    "url": "google.com",
    "status": "LEARNING",
}