POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Thuy",
    "password": "19052007"
}

###
GET http://localhost:5000/api/posts

###

POST http://localhost:5000/api/posts
Content-Type: application/json

{
    "title": "My first post",
    "description": "abc",
    "url": "google.com",
    "status": "LEARNING",
}